application:
  name: users
  version: 1.0
  title: Users
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  h2:
    console:
      enabled: true
  application:
    name: user-microservice
  datasource:
    driverClassName: org.h2.Driver
    initialization-mode: always
    initialize: true
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/